package guiwebbanking;


import javax.swing.JOptionPane;

/**
 *
 * @author Maria Melgarejo
 */
public class VentanaAcercaDelSistema extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAcercaDelSistema
     */
    public VentanaAcercaDelSistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FacultadPolitecnica = new javax.swing.JLabel();
        jLabelLenguajesDeProgramacionII = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelExamenFinal = new javax.swing.JLabel();
        jLabelGrupo9 = new javax.swing.JLabel();
        jLabelintegrantes = new javax.swing.JLabel();
        jLabelCielito = new javax.swing.JLabel();
        jLabelManuel = new javax.swing.JLabel();
        jLabelSofia = new javax.swing.JLabel();
        jLabelIvan = new javax.swing.JLabel();
        jButtonVerDocumentacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FacultadPolitecnica.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FacultadPolitecnica.setText("FACULTAD POLITÉCNICA");

        jLabelLenguajesDeProgramacionII.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelLenguajesDeProgramacionII.setText("Lenguajes de Programación II");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fpuna_logo_institucional.png"))); // NOI18N

        jLabelExamenFinal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelExamenFinal.setText("Examen Final - 2023");

        jLabelGrupo9.setText("Grupo N° 9");

        jLabelintegrantes.setText("Integrantes");

        jLabelCielito.setText("Maria Cielito Melgarejo Baez");

        jLabelManuel.setText("Manuel Antonio Agüero Vera");

        jLabelSofia.setText("Sofia Monserrat Sanabria Estigarribia");

        jLabelIvan.setText("Ivan Alejandro Figueredo Cañete");

        jButtonVerDocumentacion.setText("Ver Documentación");
        jButtonVerDocumentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerDocumentacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonVerDocumentacion)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FacultadPolitecnica)
                                .addComponent(jLabelExamenFinal)
                                .addComponent(jLabelLenguajesDeProgramacionII)))
                        .addGap(44, 44, 44)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelintegrantes)
                            .addComponent(jLabelGrupo9)
                            .addComponent(jLabelIvan)
                            .addComponent(jLabelSofia)
                            .addComponent(jLabelManuel)
                            .addComponent(jLabelCielito))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(FacultadPolitecnica)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLenguajesDeProgramacionII)
                        .addGap(29, 29, 29)
                        .addComponent(jLabelExamenFinal))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jButtonVerDocumentacion)
                .addGap(21, 21, 21)
                .addComponent(jLabelGrupo9)
                .addGap(18, 18, 18)
                .addComponent(jLabelintegrantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCielito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelManuel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSofia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIvan)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerDocumentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerDocumentacionActionPerformed
        try {
            // Especificar la ruta completa al directorio del javadoc
            String rutaJavadoc = "C:\\Users\\laser\\Downloads\\GUIWebBanking (1)\\GUIWebBanking (4)\\GUIWebBanking\\dist\\javadoc\\index.html";

            // Crear un objeto File con la ruta del javadoc
            java.io.File javadocFile = new java.io.File(rutaJavadoc);

            if (javadocFile.exists()) {
                // Obtener la URL del javadoc
                java.net.URL url = javadocFile.toURI().toURL();

                // Abrir la documentación en el navegador predeterminado
                java.awt.Desktop.getDesktop().browse(url.toURI());
            } else {
                // Mostrar un mensaje si no se encuentra la documentación
                JOptionPane.showMessageDialog(this, "No se ha encontrado la documentación en la ruta especificada.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            // Manejar la excepción 
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonVerDocumentacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAcercaDelSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAcercaDelSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAcercaDelSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAcercaDelSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAcercaDelSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FacultadPolitecnica;
    private javax.swing.JButton jButtonVerDocumentacion;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCielito;
    private javax.swing.JLabel jLabelExamenFinal;
    private javax.swing.JLabel jLabelGrupo9;
    private javax.swing.JLabel jLabelIvan;
    private javax.swing.JLabel jLabelLenguajesDeProgramacionII;
    private javax.swing.JLabel jLabelManuel;
    private javax.swing.JLabel jLabelSofia;
    private javax.swing.JLabel jLabelintegrantes;
    // End of variables declaration//GEN-END:variables
}
